version: "2"
run:
  concurrency: 0
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - unconvert
    - nolintlint
    - bodyclose
    - cyclop

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-type-assertions: true
      check-blank: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

formatters:
  enable:
    - goimports
    - gofumpt
