// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: action_items.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteActionItemsForMeeting = `-- name: DeleteActionItemsForMeeting :exec
DELETE FROM action_items WHERE meeting_id = $1
`

func (q *Queries) DeleteActionItemsForMeeting(ctx context.Context, meetingID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteActionItemsForMeeting, meetingID)
	return err
}

const insertActionItem = `-- name: InsertActionItem :one
INSERT INTO action_items (meeting_id, user_id, description, assignee, due_text, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, meeting_id, user_id, description, assignee, due_text, done, sort_order, created_at, updated_at
`

type InsertActionItemParams struct {
	MeetingID   uuid.UUID
	UserID      uuid.UUID
	Description string
	Assignee    string
	DueText     string
	SortOrder   int32
}

func (q *Queries) InsertActionItem(ctx context.Context, arg InsertActionItemParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, insertActionItem,
		arg.MeetingID,
		arg.UserID,
		arg.Description,
		arg.Assignee,
		arg.DueText,
		arg.SortOrder,
	)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.UserID,
		&i.Description,
		&i.Assignee,
		&i.DueText,
		&i.Done,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActionItemsByMeeting = `-- name: ListActionItemsByMeeting :many
SELECT id, meeting_id, user_id, description, assignee, due_text, done, sort_order, created_at, updated_at FROM action_items WHERE meeting_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListActionItemsByMeeting(ctx context.Context, meetingID uuid.UUID) ([]ActionItem, error) {
	rows, err := q.db.Query(ctx, listActionItemsByMeeting, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionItem
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.UserID,
			&i.Description,
			&i.Assignee,
			&i.DueText,
			&i.Done,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingActionItemsForUser = `-- name: ListPendingActionItemsForUser :many
SELECT ai.id, ai.meeting_id, ai.user_id, ai.description, ai.assignee, ai.due_text, ai.done, ai.sort_order, ai.created_at, ai.updated_at, m.title AS meeting_title
FROM action_items ai
JOIN meetings m ON m.id = ai.meeting_id
WHERE ai.user_id = $1 AND ai.done = false
ORDER BY ai.created_at DESC
LIMIT 100
`

type ListPendingActionItemsForUserRow struct {
	ID           uuid.UUID
	MeetingID    uuid.UUID
	UserID       uuid.UUID
	Description  string
	Assignee     string
	DueText      string
	Done         bool
	SortOrder    int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	MeetingTitle string
}

func (q *Queries) ListPendingActionItemsForUser(ctx context.Context, userID uuid.UUID) ([]ListPendingActionItemsForUserRow, error) {
	rows, err := q.db.Query(ctx, listPendingActionItemsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingActionItemsForUserRow
	for rows.Next() {
		var i ListPendingActionItemsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.UserID,
			&i.Description,
			&i.Assignee,
			&i.DueText,
			&i.Done,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MeetingTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActionItemDone = `-- name: SetActionItemDone :one
UPDATE action_items
SET done = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, meeting_id, user_id, description, assignee, due_text, done, sort_order, created_at, updated_at
`

type SetActionItemDoneParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Done   bool
}

func (q *Queries) SetActionItemDone(ctx context.Context, arg SetActionItemDoneParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, setActionItemDone, arg.ID, arg.UserID, arg.Done)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.UserID,
		&i.Description,
		&i.Assignee,
		&i.DueText,
		&i.Done,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
