// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listArtifactsByMeeting = `-- name: ListArtifactsByMeeting :many
SELECT id, meeting_id, artifact_type, content, created_at FROM artifacts WHERE meeting_id = $1 ORDER BY artifact_type
`

func (q *Queries) ListArtifactsByMeeting(ctx context.Context, meetingID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByMeeting, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.ArtifactType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtifact = `-- name: UpsertArtifact :one
INSERT INTO artifacts (meeting_id, artifact_type, content)
VALUES ($1, $2, $3)
ON CONFLICT (meeting_id, artifact_type) DO UPDATE SET content = EXCLUDED.content
RETURNING id, meeting_id, artifact_type, content, created_at
`

type UpsertArtifactParams struct {
	MeetingID    uuid.UUID
	ArtifactType string
	Content      string
}

func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, upsertArtifact, arg.MeetingID, arg.ArtifactType, arg.Content)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.ArtifactType,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
