// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meetings.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMeeting = `-- name: CreateMeeting :one
INSERT INTO meetings (user_id, title, audio_gcs_path, status, scheduled_at, remind_before_min)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, audio_gcs_path, status, transcript, duration_seconds, error_message, scheduled_at, remind_before_min, processed_at, created_at, updated_at
`

type CreateMeetingParams struct {
	UserID          uuid.UUID
	Title           string
	AudioGcsPath    string
	Status          string
	ScheduledAt     *time.Time
	RemindBeforeMin int32
}

func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, createMeeting,
		arg.UserID,
		arg.Title,
		arg.AudioGcsPath,
		arg.Status,
		arg.ScheduledAt,
		arg.RemindBeforeMin,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.AudioGcsPath,
		&i.Status,
		&i.Transcript,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.ScheduledAt,
		&i.RemindBeforeMin,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeetingForUser = `-- name: GetMeetingForUser :one
SELECT id, user_id, title, audio_gcs_path, status, transcript, duration_seconds, error_message, scheduled_at, remind_before_min, processed_at, created_at, updated_at FROM meetings WHERE id = $1 AND user_id = $2
`

type GetMeetingForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMeetingForUser(ctx context.Context, arg GetMeetingForUserParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, getMeetingForUser, arg.ID, arg.UserID)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.AudioGcsPath,
		&i.Status,
		&i.Transcript,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.ScheduledAt,
		&i.RemindBeforeMin,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMeetingStatus = `-- name: UpdateMeetingStatus :one
UPDATE meetings
SET status = $2, updated_at = now()
WHERE id = $1 AND status = $3
RETURNING id, user_id, title, audio_gcs_path, status, transcript, duration_seconds, error_message, scheduled_at, remind_before_min, processed_at, created_at, updated_at
`

type UpdateMeetingStatusParams struct {
	ID         uuid.UUID
	ToStatus   string
	FromStatus string
}

func (q *Queries) UpdateMeetingStatus(ctx context.Context, arg UpdateMeetingStatusParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, updateMeetingStatus, arg.ID, arg.ToStatus, arg.FromStatus)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.AudioGcsPath,
		&i.Status,
		&i.Transcript,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.ScheduledAt,
		&i.RemindBeforeMin,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
