// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Artifact struct {
	ID           uuid.UUID
	MeetingID    uuid.UUID
	ArtifactType string
	Content      string
	CreatedAt    time.Time
}

type Meeting struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Title           string
	AudioGcsPath    string
	Status          string
	Transcript      string
	DurationSeconds int32
	ErrorMessage    string
	ScheduledAt     *time.Time
	RemindBeforeMin int32
	ProcessedAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	RemindedAt      *time.Time
}

type PushSubscription struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Endpoint  string
	P256dhKey string
	AuthKey   string
	CreatedAt time.Time
}

type User struct {
	ID          uuid.UUID
	FirebaseUid string
	Email       string
	DisplayName string
	AvatarUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
