// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

type ActionItem struct {
	ID          uuid.UUID
	MeetingID   uuid.UUID
	UserID      uuid.UUID
	Description string
	Assignee    string
	DueText     string
	Done        bool
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DueAt       *time.Time
	RemindedAt  *time.Time
	Source      string
}

type Artifact struct {
	ID           uuid.UUID
	MeetingID    uuid.UUID
	ArtifactType string
	Content      string
	CreatedAt    time.Time
}

type Meeting struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Title              string
	AudioGcsPath       string
	Status             string
	Transcript         string
	DurationSeconds    int32
	ErrorMessage       string
	ScheduledAt        *time.Time
	RemindBeforeMin    int32
	ProcessedAt        *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	RemindedAt         *time.Time
	TranscriptSegments []byte
	SpeakerNames       []byte
	Summary            string
	Scenario           string
	SummarySections    []byte
}

type PushSubscription struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Endpoint  string
	P256dhKey string
	AuthKey   string
	CreatedAt time.Time
}

type TranscriptChunk struct {
	ID         uuid.UUID
	MeetingID  uuid.UUID
	UserID     uuid.UUID
	ChunkIndex int32
	Content    string
	Embedding  *pgvector.Vector
	CreatedAt  time.Time
}

type User struct {
	ID          uuid.UUID
	FirebaseUid string
	Email       string
	DisplayName string
	AvatarUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
