/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康檢查 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登入後同步用戶（以 firebase_uid upsert）
         * @description 前端完成 Google 登入後呼叫；非白名單 email 回 403。
         */
        post: operations["syncUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 本人會議列表（新→舊，可關鍵字搜尋） */
        get: operations["listMeetings"];
        put?: never;
        /**
         * 建立會議並取得音訊直傳 URL
         * @description 回傳的 upload.url 供前端直接 PUT 音訊到 GCS（需帶 upload.headers）；上傳完成後呼叫 complete-upload。
         */
        post: operations["createMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/scheduled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 建立排程會議（會前推播提醒） */
        post: operations["createScheduledMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改排程（重置提醒） */
        patch: operations["updateMeetingSchedule"];
        trace?: never;
    };
    "/api/v1/push/vapid-public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Web Push VAPID 公鑰 */
        get: operations["getVapidPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 註冊推播訂閱 */
        post: operations["subscribePush"];
        /** 取消推播訂閱 */
        delete: operations["unsubscribePush"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 會議詳情（含逐字稿） */
        get: operations["getMeeting"];
        put?: never;
        post?: never;
        /** 刪除排程會議（僅 scheduled 狀態，本人限定） */
        delete: operations["deleteScheduledMeeting"];
        options?: never;
        head?: never;
        /** 重新命名會議（任何狀態，本人限定） */
        patch: operations["renameMeeting"];
        trace?: never;
    };
    "/api/v1/meetings/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重跑失敗的會議 */
        post: operations["retryMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{id}/complete-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 音訊直傳完成，觸發背景處理
         * @description 驗證物件已存在後將狀態推進為 pending 並排入處理佇列；對已處理中的會議冪等。
         */
        post: operations["completeMeetingUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取回會議的 AI 生成文件（PRD / Tech Spec） */
        get: operations["listMeetingArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{id}/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取回會議的行動項 */
        get: operations["listMeetingActionItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 跨會議的未完成行動項 */
        get: operations["listPendingActionItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 標記行動項完成 / 取消完成 */
        patch: operations["toggleActionItem"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 統一 response envelope */
        Envelope: {
            /**
             * @description 0 = 成功；非 0 為業務錯誤碼（HTTP status 三碼 + 兩碼流水號）
             * @example 0
             */
            errCode: number;
            /** @example success */
            msg: string;
            /** @example 43499282e559d33a */
            traceId?: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            avatarUrl: string;
            /** Format: date-time */
            createdAt: string;
        };
        Meeting: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            status: "scheduled" | "pending" | "transcribing" | "analyzing" | "completed" | "failed";
            durationSeconds: number;
            errorMessage?: string;
            /** Format: date-time */
            scheduledAt?: string;
            remindBeforeMin: number;
            /** Format: date-time */
            createdAt: string;
            /** @description 搜尋命中的逐字稿片段（僅 search 非空且語意命中時出現） */
            matchSnippet?: string;
            /**
             * @description 命中類型
             * @enum {string}
             */
            matchType?: "semantic" | "literal";
        };
        MeetingDetail: components["schemas"]["Meeting"] & {
            transcript: string;
        };
        Artifact: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "prd" | "tech_spec";
            /** @description Markdown 全文 */
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        ActionItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            meetingId: string;
            description: string;
            /** @description 負責人；會議未指派時為空字串 */
            assignee: string;
            /** @description 時限（原文說法）；會議未提及時為空字串 */
            dueText: string;
            done: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        PendingActionItem: components["schemas"]["ActionItem"] & {
            meetingTitle: string;
        };
    };
    responses: {
        /** @description 未帶有效 Firebase ID token（errCode 40101） */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description email 不在白名單（errCode 40301） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服務正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            /** @example ok */
                            status?: string;
                            /** @example local */
                            env?: string;
                        };
                    };
                };
            };
        };
    };
    syncUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 同步成功，回傳用戶資料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listMeetings: {
        parameters: {
            query?: {
                /** @description 關鍵字（比對 title 與 transcript，ILIKE） */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 列表（不含 transcript） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            meetings: components["schemas"]["Meeting"][];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 架構討論會議 */
                    title: string;
                    /**
                     * @description 音訊 MIME type（audio/mpeg, audio/mp4, audio/x-m4a, audio/webm, audio/wav）
                     * @example audio/webm
                     */
                    contentType: string;
                };
            };
        };
        responses: {
            /** @description 建立成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            meeting: components["schemas"]["Meeting"];
                            upload: {
                                url: string;
                                headers: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
            /** @description title 空白或 contentType 不支援（errCode 40001） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createScheduledMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    /** Format: date-time */
                    scheduledAt: string;
                    /** @default 15 */
                    remindBeforeMin?: number;
                };
            };
        };
        responses: {
            /** @description 已建立（status = scheduled） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            meeting?: components["schemas"]["Meeting"];
                        };
                    };
                };
            };
            /** @description title 空白或時間非未來（errCode 40001） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMeetingSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    /** Format: date-time */
                    scheduledAt: string;
                    remindBeforeMin?: number;
                };
            };
        };
        responses: {
            /** @description 已更新，reminded_at 清除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            meeting?: components["schemas"]["Meeting"];
                        };
                    };
                };
            };
            /** @description 不存在、非本人或非 scheduled 狀態 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    getVapidPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公鑰 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            publicKey?: string;
                        };
                    };
                };
            };
        };
    };
    subscribePush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    endpoint: string;
                    keys: {
                        p256dh: string;
                        auth: string;
                    };
                };
            };
        };
        responses: {
            /** @description 已訂閱 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    unsubscribePush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    endpoint: string;
                };
            };
        };
        responses: {
            /** @description 已取消 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    getMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 詳情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            meeting: components["schemas"]["MeetingDetail"];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 不存在或非本人（errCode 40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    deleteScheduledMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已刪除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description 不存在、非本人或非 scheduled 狀態 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    renameMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                };
            };
        };
        responses: {
            /** @description 已更名 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            meeting?: components["schemas"]["Meeting"];
                        };
                    };
                };
            };
            /** @description 不存在或非本人 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    retryMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已重新排入（status 回到 pending） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            meeting: components["schemas"]["Meeting"];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 不存在或非本人 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description 非 failed 狀態不可重跑（errCode 40901） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    completeMeetingUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已進入處理佇列（或已在處理中） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            meeting: components["schemas"]["Meeting"];
                        };
                    };
                };
            };
            /** @description 音訊尚未上傳（errCode 40001） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 會議不存在或非本人所有（errCode 40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description 狀態衝突（errCode 40901） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listMeetingArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文件清單（處理未完成時可能為空陣列） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            artifacts: components["schemas"]["Artifact"][];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 會議不存在或非本人所有（errCode 40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listMeetingActionItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 行動項清單（處理未完成或無行動項時為空陣列） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            actionItems: components["schemas"]["ActionItem"][];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 會議不存在或非本人所有（errCode 40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listPendingActionItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 本人所有未完成行動項（含所屬會議標題） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            actionItems: components["schemas"]["PendingActionItem"][];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    toggleActionItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    done: boolean;
                };
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            actionItem: components["schemas"]["ActionItem"];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 行動項不存在或非本人所有（errCode 40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
}
